#adapted from example in docker documentation
version: '3'

services:
  web:
    build: .
    restart: always
    volumes:
       - .:/code
    expose:
      - 8000
    user: 1001:1002
    # ports:
    #    - 8000:8000
    #user: 1000:1000 # use if you are working in Linux/Ubuntu
    #command: python /code/mysite/manage.py runserver 0.0.0.0:8000
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/code/mysite/cins465-cloudkey.json
    working_dir: /code/mysite
    command: daphne -b 0.0.0.0 -p 8000 mysite.asgi:application

  # nginx:
  #   restart: always
  #   build: ./nginx/
  #   depends_on:
  #     - web
  #   ports:
  #     - 80:80
  #     - 443:443
  #   links:
  #     - web:web
  #   volumes:
  #     - ./mysite/static/:/static

  wasm:
    build: ./wasm/
    environment:
      - USER=shelleywong
    working_dir: /code/hello-wasm
    volumes: 
      - .:/code

  caddy:
    image: caddy:latest
    restart: unless-stopped
    depends_on:
      - web
    links:
      - web:web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - $PWD/mysite/static:/srv/static/
      - $PWD/hello-wasm/pkg/:/srv/wasm
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:





