#adapted from example in docker documentation
version: '3'

services:
  web:
    build: .
    restart: always
    volumes:
       - .:/code
    expose:
      - 8000
    user: 1001:1002
    # ports:
    #    - 8000:8000
    #user: 1000:1000 # use if you are working in Linux/Ubuntu
    command: python /code/mysite/manage.py runserver 0.0.0.0:8000

  nginx:
    restart: always
    build: ./nginx/
    depends_on:
      - web
    ports:
      - 80:80
    links:
      - web:web

