# Generated by Django 4.1 on 2022-09-20 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_questionmodel_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionmodel',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
